My i18n
mpg-yuya-nishimura/fjord-books_app-2023 pull request #1
Opened 2023-07-21 10:41 UTC by medyuya

## やったこと
英語・日本語の表示切り替えの実装

レビューよろしくお願いします！

2023-07-27 15:54 UTC, u1tnk requested changes
プラクティスの必須要件の

> [Rails 国際化 (i18n) API - Railsガイド](https://railsguides.jp/i18n.html) を読み、使えそうなメソッドがあれば積極的に使う

が対応されていないので見てみてください

2023-08-02 11:38 UTC, medyuya commented
>プラクティスの必須要件の[Rails 国際化 (i18n) API - Railsガイド](https://railsguides.jp/i18n.html) を読み使えそうなメソッドがあれば積極的に使うが対応されていないので見てみてください

こちら、対応しました！

2023-08-02 14:54 UTC, u1tnk requested changes
human_attibute_name使えたのは良いですね！

Model.model_name.human の方も使ってください 🙏

2023-08-08 10:24 UTC, medyuya commented
Model.model_name.humanも使いました！
再度レビューよろしくお願いします！

2023-08-09 15:27 UTC, u1tnk approved these changes

2023-08-24 12:34 UTC, merged