My comments
mpg-yuya-nishimura/fjord-books_app-2023 pull request #7
Opened 2023-08-08 06:31 UTC by medyuya

## やったこと
・日報のCRUDの実装
・本・日報へのコメント機能の実装

レビューよろしくお願いします！＾＾

2023-08-08 06:34 UTC, medyuya commented on app/controllers/reports_controller.rb
> +    @comments = @report.comments.preload(:user)
preload(:user)でN+1対応しています。

2023-08-08 06:34 UTC, medyuya commented on app/controllers/books_controller.rb
> +    @comments = @book.comments.preload(:user)
preload(:user)でN+1対応しています。

2023-08-08 06:54 UTC, medyuya commented
以下がデモ動画になります！

## 日報のDRUD
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/d2bbe442-c062-412f-93ae-71406df0cbbf

## コメントの作成・削除
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/9a5fe5f4-39cf-44c8-a40c-ca36b819f4d3

2023-08-14 15:50 UTC, u1tnk requested changes
コメントしました！
同じ問題は一回しかコメントしてないので他の箇所も適宜反映してください。

2023-08-14 15:50 UTC, u1tnk commented on Gemfile
> +gem 'pry-rails'
[修正不要]
最近は irbが便利になってるので pryは使われなくなってきましたね。

2023-08-14 15:50 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @comment.destroy
必ず成功するはずのところであれば `destroy!` にしましょう。
不具合などで失敗したときに検知できるようになります。

2023-08-14 15:50 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
validation errorのときは redirectせずに renderしましょう。 `@comment` に入っているエラー情報が取れなくなってしまいます。
共通化がしたくてやってるんだと思いますが無理に共通化しなくて大丈夫ですよ。

2023-08-14 15:50 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +  def correct_user
名前が良くないですね。
この名前だと`正しいユーザ`が返ってきそうなのでもうちょっと具体的にしましょう。

2023-08-14 15:50 UTC, u1tnk commented on app/helpers/comments_helper.rb
> +module CommentsHelper
生成されたファイルと思いますが、特に何もしないhelperは消しちゃって良いですよ。

2023-08-14 15:50 UTC, u1tnk commented on db/migrate/20230802123357_create_reports.rb
> +      t.string :title
必須のものは `null: false` を付けるようにした方が良いですね。

2023-08-14 15:50 UTC, u1tnk commented on app/models/report.rb
> +  has_many :comments, as: :commentable, dependent: :destroy
必須の値は htmlだけじゃなくてmodelにも 必須チェックをかけるようにしましょう。
html上の制限はいくらでも無視できるものなので。

2023-08-14 15:50 UTC, u1tnk commented on app/views/books/show.html.erb
> +<%= render 'comments/comments', comments: @comments %>
補足です。
無理に対応しなくても良いですが、以下のようにすると効率的に複数の値の表示ができます。

https://railsguides.jp/layouts_and_rendering.html#%E3%82%B3%E3%83%AC%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E3%83%AC%E3%83%B3%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0%E3%81%99%E3%82%8B

2023-08-15 10:06 UTC, mpg-yuya-nishimura commented on db/migrate/20230802123357_create_reports.rb
> +      t.string :title
つけました！(日報だけでなく、コメントの方にも追加しました！)

2023-08-15 10:13 UTC, medyuya commented on app/helpers/comments_helper.rb
> +module CommentsHelper
削除しました！
(他にも使用していないhelperがありましたが、もともとあったやつは、消していません)

2023-08-15 10:20 UTC, mpg-yuya-nishimura commented on app/models/report.rb
> +  has_many :comments, as: :commentable, dependent: :destroy
コメントと同時に、バリデーションを用意しました！

2023-08-15 10:27 UTC, medyuya commented on app/views/books/show.html.erb
> +<%= render 'comments/comments', comments: @comments %>
`<%= render @comments %>`

としてみました！

2023-08-15 10:27 UTC, medyuya commented on app/models/report.rb
> +  has_many :comments, as: :commentable, dependent: :destroy
バリデーションを加えました！

2023-08-15 10:49 UTC, medyuya commented on app/controllers/reports_controller.rb
> +  def correct_user
authorize_report_ownerとしました！

2023-08-15 10:52 UTC, medyuya commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
変更しました！

2023-08-15 10:57 UTC, medyuya commented on app/controllers/comments_controller.rb
> +    @comment.destroy
変更しました！

また、ここに関してお聞きしたいことがあります！
こう言ったデータの削除の時は、

`@report.destroy!`
のように書くことが多くみられますが、

```
if @report.destroy
 else
end
```
のように、成功・失敗で条件分岐させないのは、どうしてでしょうか？
不具合などで失敗したときに、`destroy!`だと例外処理が実行されアプリが止まってしまうように思います。

2023-08-15 11:12 UTC, medyuya commented
以下がデモ動画になります！

## 日報のDRUD
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/a48e4c38-a5ae-4807-8bcb-a6beebc3ceee


## コメントの作成・削除
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/043484c2-b772-4d31-8217-995c41bb2e7c

2023-08-15 14:10 UTC, u1tnk commented on app/controllers/comments_controller.rb
> +    @comment.destroy
削除ボタンについては入力値は特に無いのでvalidationにひっかかることはバグのときしか無いからですね。
同じようなケースでは削除じゃなくても `save!` を使うこともありますね。

2023-08-15 14:17 UTC, u1tnk requested changes
日報の方は大丈夫でしたが、コメントでvalidation errorになるようなデータを入力するとエラーになってしまいますね。

![image](https://github.com/medyuya/fjord-books_app-2023/assets/279240/c3d395c9-a67d-4b2f-b26c-5942601e894f)

2023-08-16 12:10 UTC, medyuya commented
以下がデモ動画になります！

# 日報のDRUD
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/ef761e53-e852-46b2-a5e1-daedb4d53921

# コメントの作成・削除
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/fff71eb0-5fe2-41f2-814b-e1e50064686f

# バリデーション処理
https://github.com/medyuya/fjord-books_app-2023/assets/136453544/5d765d57-47f4-4b9b-b6a5-03e54ef995a7

2023-08-16 12:25 UTC, medyuya commented on app/views/reports/show.html.erb
> +  <%= render 'reports/report', report: @report %>
<%= render @report %>
としていたのですが、バリデーション発生時に、missing Templateエラーが出てしまいました。パスを明示する方に変えました(これだと何故かうまく表示されます)。

2023-08-16 12:25 UTC, medyuya commented on app/views/books/show.html.erb
> +  <%= render 'books/book', book: @book %>
<%= render @book %>
としていたのですが、バリデーション発生時に、missing Templateエラーが出てしまいました。パスを明示する方に変えました(これだと何故かうまく表示されます)。

2023-08-17 11:21 UTC, u1tnk approved these changes
コメントしましたが修正は問題無いです！

2023-08-17 11:21 UTC, u1tnk commented on app/views/books/show.html.erb
> +  <%= render 'books/book', book: @book %>
debugしましたが通常は `books/book`を読んでますが、 バリデーションエラー発生時は `books/books/_book ` を探しているようでした。
まあ controllerなどで showなどを使うのはよくやりますが、partialのときは指定するのが一般的と思うのでこのコードで良いとは思います。
申し訳無いですが、ちょっと理由までわからなかったので、もし気になるようでしたら Q&Aに出してもらえればと思います 🙏

2023-08-24 12:35 UTC, merged